version: '3'
services:
  php_novita:
    build: ./php
    image: php:latest
    container_name: php_novita
    hostname: "php"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx_novita:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_novita
    hostname: "nginx"
    ports:
      - "24:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_novita
